# Generated by Django 4.1.3 on 2023-08-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
